export const products = [
    { nome: "Camiseta Estampada", preco: 49.90, categoria: "Roupas", disponibilidade: true },
    { nome: "Tênis Esportivo", preco: 199.90, categoria: "Calçados", disponibilidade: true },
    { nome: "Mochila de Couro", preco: 120.00, categoria: "Acessórios", disponibilidade: false },
    { nome: "Smartphone Android", preco: 1299.00, categoria: "Eletrônicos", disponibilidade: true },
    { nome: "Sofá Retrátil", preco: 2499.00, categoria: "Móveis", disponibilidade: true },
    { nome: "Cubo Mágico", preco: 25.00, categoria: "Brinquedos e Jogos", disponibilidade: false },
    { nome: "Jaqueta de Couro", preco: 300.00, categoria: "Roupas", disponibilidade: false },
    { nome: "Relógio de Pulso", preco: 150.00, categoria: "Acessórios", disponibilidade: false },
    { nome: "Fone de Ouvido Bluetooth", preco: 199.90, categoria: "Eletrônicos", disponibilidade: true },
    { nome: "Cadeira de Escritório", preco: 599.00, categoria: "Móveis", disponibilidade: false },
    { nome: "Blusa de Frio", preco: 79.90, categoria: "Roupas", disponibilidade: false },
    { nome: "Bota de Couro", preco: 249.90, categoria: "Calçados", disponibilidade: false },
    { nome: "Carteira de Couro", preco: 89.90, categoria: "Acessórios", disponibilidade: true },
    { nome: "Laptop Gamer", preco: 4999.00, categoria: "Eletrônicos", disponibilidade: false },
    { nome: "Estante de Madeira", preco: 599.00, categoria: "Móveis", disponibilidade: false },
    { nome: "Papel de Parede", preco: 69.90, categoria: "Móveis", disponibilidade: true },
    { nome: "Camiseta Básica", preco: 39.90, categoria: "Roupas", disponibilidade: false },
    { nome: "Tênis Casual", preco: 159.90, categoria: "Calçados", disponibilidade: false },
    { nome: "Relógio de Pulso de Ouro", preco: 799.90, categoria: "Acessórios", disponibilidade: false },
    { nome: "Câmera DSLR", preco: 3500.00, categoria: "Eletrônicos", disponibilidade: true },
    { nome: "Espelho Oval", preco: 150.00, categoria: "Móveis", disponibilidade: false },
    { nome: "Boneca de Pano", preco: 45.00, categoria: "Brinquedos e Jogos", disponibilidade: true },
    { nome: "Jaqueta Jeans", preco: 120.00, categoria: "Roupas", disponibilidade: true },
    { nome: "Tênis de Corrida", preco: 179.90, categoria: "Calçados", disponibilidade: false },
    { nome: "Óculos de Sol", preco: 89.90, categoria: "Acessórios", disponibilidade: true },
    { nome: "Tablet 10", preco: 899.00, categoria: "Eletrônicos", disponibilidade: true },
    { nome: "Poltrona Decorativa", preco: 499.90, categoria: "Móveis", disponibilidade: true },
    { nome: "Travesseiro de Memória", preco: 120.00, categoria: "Móveis", disponibilidade: false },
    { nome: "Cadeira de Rodas", preco: 800.00, categoria: "Móveis", disponibilidade: false },
    { nome: "Boné Estampado", preco: 59.90, categoria: "Acessórios", disponibilidade: true },
    { nome: "Triciclo Infantil", preco: 189.90, categoria: "Brinquedos e Jogos", disponibilidade: true },
    { nome: "Blusa de Manga Longa", preco: 79.90, categoria: "Roupas", disponibilidade: true },
    { nome: "Tênis de Skate", preco: 159.90, categoria: "Calçados", disponibilidade: true },
    { nome: "Smartwatch Fitness", preco: 299.90, categoria: "Eletrônicos", disponibilidade: true },
    { nome: "Conjunto de Panelas", preco: 299.00, categoria: "Móveis", disponibilidade: true },
    { nome: "Cafeteira Elétrica", preco: 159.00, categoria: "Eletrônicos", disponibilidade: true },
    { nome: "Cadeira de Jantar", preco: 150.00, categoria: "Móveis", disponibilidade: true },
    { nome: "Mouse Gamer", preco: 129.90, categoria: "Eletrônicos", disponibilidade: true },
    { nome: "Kit de Maquiagem", preco: 89.90, categoria: "Acessórios", disponibilidade: true },
    { nome: "Cadeira Gamer", preco: 1199.00, categoria: "Móveis", disponibilidade: true },
    { nome: "Camiseta Básica de Algodão", preco: 29.90, categoria: "Roupas", disponibilidade: true },
    { nome: "Bolsa Feminina", preco: 150.00, categoria: "Acessórios", disponibilidade: true },
    { nome: "Carrinho de Bebê", preco: 999.00, categoria: "Brinquedos e Jogos", disponibilidade: false },
    { nome: "Camiseta Polo", preco: 89.90, categoria: "Roupas", disponibilidade: true },
    { nome: "Tênis de Corrida Profissional", preco: 349.90, categoria: "Calçados", disponibilidade: true },
    { nome: "Jogo de Cama", preco: 119.90, categoria: "Móveis", disponibilidade: true },
    { nome: "Óculos de Leitura", preco: 50.00, categoria: "Acessórios", disponibilidade: true },
    { nome: "Bolsa de Viagem", preco: 250.00, categoria: "Acessórios", disponibilidade: true },
    { nome: "Café em Grãos", preco: 29.90, categoria: "Móveis", disponibilidade: true }
];
